ImGui class
gardzielb/EngineerToBeDx12 pull request #4
Opened 2021-09-14 18:57 UTC by gardzielb

Implemented a class encapsulating ImGui boilerplate code.

2021-09-14 20:28 UTC, jankupis requested changes

2021-09-14 20:28 UTC, jankupis commented on EngineerToBeDx12DR/imgui.ini
> +
I would include this file in gitignore

2021-09-14 20:36 UTC, gardzielb commented on EngineerToBeDx12DR/imgui.ini
> +
Good idea, done

2021-09-14 20:37 UTC, jankupis approved these changes

2021-09-20 19:35 UTC, debskipawel approved these changes
LGTM

2021-09-27 18:28 UTC, merged